### ISSUE TITLE
TODO by December

### ISSUE THREAD

**Issue by nswa17** [taulukointipalvelut/utab-server#1]
- [ ] query使うときはparseIntする
- [x] confiに色々追加
- [ ] サーバーroute分割
- [x] round指定(優先度低)(schema.js, controllers.js, utab.js)
- [x] routing
- [x] raw消す
- [x] database
- [x] 個体に対するmethod
- [x] if name(of tournament) does not exist => return 404 error
- [x] 複数create
- [x] considering roundsがcurrentを超えた場合=> checkがエラー返す.
- [x] errorsを実装/copy
- [x] adjudicator allocationのメソッド
- [x] data(null), errors([]), log(json)にする.
- [x] long_name -> name
- [x] get allocationはPATCH
- [x] numbers
- [x] 同じ名前のtournamentsが複数登録できてしまう
- [ ] 入力の形式整える

**Comment by fj68** [comment]
- [x] static fileの配信
